version: '3'

services:
    app:
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - backend_app_backend
        expose:
            - '${DOCKER_PORT}'

networks:
    backend_app_backend:
        external: true
