version: '3.8'

services:
    app-server:
        container_name: app
        image: app
        restart: no
        env_file: .env
        ports:
            - '3000:3000'
        networks:
            - postgres_app_backend
        build:
            context: .
            dockerfile: Dockerfile
            target: app
networks:
    postgres_app_backend:
        name: postgres_app_backend
        external: true
