#!/usr/bin/env bash

openssl req -nodes -new -x509 -keyout CA_key.pem -out CA_cert.pem -days 1825 -config CA.cnf

openssl req -sha256 -nodes -newkey rsa:2048 -keyout localhost_key.pem -out localhost.csr -config localhost.cnf

openssl x509 -req -days 398 -in localhost.csr -CA CA_cert.pem -CAkey CA_key.pem -CAcreateserial -out localhost_cert.pem -extensions req_ext -extfile localhost.cnf

if [[ ! -d security ]]; then
    mkdir security
fi

mv localhost_cert.pem security/
mv localhost_key.pem security/
rm ./*.pem
rm ./*.csr
rm ./*.srl
